### ISSUE TITLE
比较好的docker解决方案

### ISSUE THREAD

**Issue by MouJiaoZi** [Xerxes-2/clewdr#29]
优点：直接通过release的二进制文件运行，省去编译的超长时间

二进制文件选择musllinux版本

- Dockerfile
```
FROM alpine:latest

WORKDIR /app

# 复制二进制文件到容器
COPY clewdr /app/

# 设置执行权限
RUN chmod +x /app/clewdr

# 暴露应用端口
EXPOSE 8484

# 运行二进制文件
CMD ["./clewdr"]
```

- docker-compose.yml
```
version: '3.8'

services:
  clewdr:
    container_name: clewdr
    build: .
    ports:
      - "8446:8484" # 自行替换你需要的端口
    volumes:
      - .:/app
    working_dir: /app
    restart: always
    user: root
    # 添加容器启动时的权限修复命令
    command: sh -c "chmod +x ./clewdr && ./clewdr"
```
